### ISSUE TITLE
[Improvement] Encapsulate URL as a credentials

### ISSUE THREAD

**Issue by v1v** [alphagov/pay-jenkins-library#109]
https://github.com/alphagov/pay-jenkins-library/blob/d3eda5b5d1eb7096b63f8d2e93a64d8a575b2e4f/vars/tagPact.groovy#L11 seems to expose publicly the URL for a certain service, ideally, it could be encapsulated as a credential and access to the value using the step: https://jenkins.io/doc/pipeline/steps/credentials-binding/

**Comment by jfharden** [comment]
Hi,

We have discontinued our use of Jenkins and are archiving the repository.

Regards,

Jonathan
