### ISSUE TITLE
[Feature Request] Publish details on ZAP tests

### ISSUE THREAD

**Issue by northdpole** [alphagov/pay-jenkins-library#25]
Hi,

Came across your repo looking for OWASP ZAP testing as part of a CI pipeline,
it looks like you have integrated ZAP in your CI, is there any chance you can publish orchestration scripts and/or any other information/config you can on this?

Thanks

**Comment by whpearson** [comment]
Hi, 

We have written java based tests (currently private) which use the org.zaproxy.clientapi.core java libraries to run some zap based tests.

The tests exclude urls to not scan and also a list of alerts to ignore.  These are then run by CI.
 
Hope that helps a bit. 

  Will

**Comment by jfharden** [comment]
Hi,

We have discontinued our use of Jenkins and are archiving the repository.

Regards,

Jonathan
